### PR TITLE
fix: ENVIRONMENT_TYPE needs to be used to check onProduction()

### LINKED ISSUE #21: Config::onProduction fails if using branch name "main"
The `onProduction` method fails if you use a branch name of `main`.

```
$prodBranch = $this->onDedicated() ? 'production' : 'master';
```

### PR DESCRIPTION
**Pull request by matthiaz**
Closes #21 
Which allows onProduction to correctly identify the production environment, without having to be named 'master'

This issue is fairly old, and an attempt was made to fix this in https://github.com/platformsh/config-reader-php/pull/22
However, backwards compatibility was not maintained in there. 

This PR tries to address that backwards compatibility, so this should work for old and new environments.

### CODE REVIEW

File: src/Config.php [hunk 1]
```diff
@@ -437,9 +440,16 @@ public function onProduction() : bool
...
-
-        return $this->getValue('BRANCH') == $prodBranch;
+        // we need to first confirm that we actually have the `ENVIRONMENT_TYPE` variable, 
+        // because not all legacy containers will have this
+        if($this->hasVariable('ENVIRONMENT_TYPE')) {
+            // correct way of checking production branch
+            return $this->getValue('ENVIRONMENT_TYPE') == 'production';
+        } else {
+            // legacy way of checking production type
+            $prodBranch = $this->onDedicated() ? 'production' : 'master';
```
Comment (flovntp) [inline src/Config.php:450]: `master` ?

Comment (matthiaz) [reply src/Config.php:450]: well yeah, that's the backwards compatibility. Ideally we won't ever get into this else statement. But if we do, the functionality needs to be the same.
